ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false

    odom0: /odometry/gps
    imu0: /imu/data

    odom0_config: [true, true, true,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    odom0_differential: false
    imu0_differential: false
    use_control: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

