navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true

    publish_filtered_gps: true
    use_odometry_yaw: true

    gps_topic: /fix
    imu_topic: /imu/data
    odom_topic: /odometry/gps

